advancedMode: true
colorThemeName: plum's purple palace
comboizeSelect: true
cursorTrailGhost: false
cursorTrailIndex: 1
cursorTrailPoints: 20
cursorTrailShapeIndex: 2
cursorTrailSize: 10
customStyles:
- 
defaultProperties:
  settings:
    linearVibratoSV:
      startMsx: 100
      endMsx: 0
    polynomialVibratoSV:
      startMsx: 0
      endMsx: 100
      controlPointCount: 3
      controlPoints:
      - - 0.25
        - 0.25
      - - 0.5
        - 0
      - - 0.75
        - 0.25
      plotPoints:
      - 
      plotCoefficients:
      - 
    exponentialVibratoSV:
      startMsx: 100
      endMsx: 0
      curvatureIndex: 5
    sinusoidalVibratoSV:
      startMsx: 100
      endMsx: 0
      verticalShift: 0
      periods: 1
      periodsShift: 0.25
    sigmoidalVibratoSV:
      startMsx: 100
      endMsx: 0
      curvatureIndex: 5
    customVibratoSV:
      code: >-
        return function (x)
            local maxHeight = 150
            heightFactor = maxHeight * math.exp((1 - math.sqrt(17)) / 2) / (31 - 7 * math.sqrt(17)) * 16
            primaryCoefficient = (x^2 - x^3) * math.exp(2 * x)
            sinusoidalCoefficient = math.sin(8 * math.pi * x)
            return heightFactor * primaryCoefficient * sinusoidalCoefficient
        end
    linearVibratoSSF:
      lowerStart: 0.5
      lowerEnd: 0.5
      higherStart: 1
      higherEnd: 1
    exponentialVibratoSSF:
      lowerStart: 0.5
      lowerEnd: 0.5
      higherStart: 1
      higherEnd: 1
      curvatureIndex: 10
    sinusoidalVibratoSSF:
      lowerStart: 0.5
      lowerEnd: 0.5
      higherStart: 1
      higherEnd: 1
      verticalShift: 0
      periods: 1
      periodsShift: 0.25
      applyToHigher: false
    sigmoidalVibratoSSF:
      lowerStart: 0.5
      lowerEnd: 0.5
      higherStart: 1
      higherEnd: 1
      curvatureIndex: 5
    customVibratoSSF:
      code1: return function (x) return 0.69 end
      code2: return function (x) return 1.420 end
    linear:
      startSV: -1.5
      endSV: 1.5
      svPoints: 16
      finalSVIndex: 2
      customSV: 1
    exponential:
      behaviorIndex: 1
      intensity: 20
      verticalShift: 0
      distance: 100
      startSV: 0.01
      endSV: 1
      avgSV: 1
      svPoints: 16
      finalSVIndex: 2
      customSV: 1
      distanceMode: 1
    bezier:
      p1:
      - 0.10000000149011612
      - 0.89999997615814209
      p2:
      - 0.89999997615814209
      - 0.10000000149011612
      verticalShift: 0
      freeMode: false
      manualMode: false
      avgSV: 1
      svPoints: 16
      finalSVIndex: 2
      customSV: 1
    hermite:
      startSV: 0
      endSV: 0
      verticalShift: 0
      avgSV: 1
      svPoints: 16
      finalSVIndex: 2
      customSV: 1
    sinusoidal:
      startSV: 1
      endSV: 1
      curveSharpness: 50
      verticalShift: 0
      periods: 1
      periodsShift: 0.25
      svsPerQuarterPeriod: 8
      svPoints: 16
      finalSVIndex: 2
      customSV: 1
    circular:
      behaviorIndex: 1
      arcPercent: 50
      avgSV: 1
      verticalShift: 0
      svPoints: 16
      finalSVIndex: 2
      customSV: 1
      dontNormalize: false
    random:
      svMultipliers:
      - 
      randomTypeIndex: 1
      randomScale: 2
      svPoints: 16
      finalSVIndex: 2
      customSV: 1
      dontNormalize: false
      avgSV: 1
      verticalShift: 0
    custom:
      svMultipliers:
      - 0
      selectedMultiplierIndex: 1
      svPoints: 1
      finalSVIndex: 2
      customSV: 1
    chinchilla:
      behaviorIndex: 1
      chinchillaTypeIndex: 1
      chinchillaIntensity: 0.5
      avgSV: 1
      verticalShift: 0
      svPoints: 16
      finalSVIndex: 2
      customSV: 1
    combo:
      svType1Index: 2
      svType2Index: 2
      comboPhase: 0
      comboTypeIndex: 4
      comboMultiplier1: 1
      comboMultiplier2: 1
      finalSVIndex: 2
      customSV: 1
      dontNormalize: false
      avgSV: 1
      verticalShift: 0
    code:
      code: >-
        return function (x)
            local startPeriod = 4
            local endPeriod = -1
            local height = 1.5
            return height * math.sin(2 * math.pi * (startPeriod * x + (endPeriod - startPeriod) / 2 * x^2))
        end
      svPoints: 64
      finalSVIndex: 2
      customSV: 1
    stutter:
      startSV: 5
      endSV: 0.5
      stutterDuration: 15
      stutterDuration2: 0
      stuttersPerSection: 1
      avgSV: 1
      finalSVIndex: 2
      customSV: 1
      linearlyChange: false
      controlLastSV: false
      svMultipliers:
      - 
      svDistances:
      - 
      svGraphStats:
        minScale: 0
        maxScale: 0
        distMinScale: 0
        distMaxScale: 0
      svMultipliers2:
      - 
      svDistances2:
      - 
      svGraph2Stats:
        minScale: 0
        maxScale: 0
        distMinScale: 0
        distMaxScale: 0
    teleportStutter:
      svPercent: 90
      svPercent2: 0
      distance: 50
      mainSV: 0.10000000149011612
      mainSV2: 0
      useDistance: false
      linearlyChange: false
      avgSV: 1
      finalSVIndex: 2
      customSV: 1
      stuttersPerSection: 1
    framesSetup:
      menuStep: 1
      numFrames: 5
      frameDistance: 2000
      distance: 2000
      reverseFrameOrder: false
      noteSkinTypeIndex: 1
      frameTimes:
      - 
      selectedTimeIndex: 1
      currentFrame: 1
    penis:
      bWidth: 50
      sWidth: 100
      sCurvature: 100
      bCurvature: 100
    automate:
      copiedSVs:
      - 
      deleteCopiedSVs: true
      maintainMs: true
      ms: 500
      scaleSVs: false
      initialSV: 1
      optimizeTGs: true
    animationPalette:
      instructions: ''
  menu:
    placeStandard:
      svTypeIndex: 1
      svMultipliers:
      - 
      svDistances:
      - 
      svGraphStats:
        minScale: 0
        maxScale: 0
        distMinScale: 0
        distMaxScale: 0
      svStats:
        minSV: 0
        maxSV: 0
        avgSV: 0
      interlace: false
      interlaceRatio: -0.5
    placeSpecial:
      svTypeIndex: 1
    placeStill:
      svTypeIndex: 1
      noteSpacing: 1
      stillTypeIndex: 1
      stillDistance: 0
      stillBehavior: 1
      prePlaceDistances:
      - 
      svMultipliers:
      - 
      svDistances:
      - 
      svGraphStats:
        minScale: 0
        maxScale: 0
        distMinScale: 0
        distMaxScale: 0
      svStats:
        minSV: 0
        maxSV: 0
        avgSV: 0
      interlace: false
      interlaceRatio: -0.5
    placeVibrato:
      svTypeIndex: 1
      vibratoMode: 1
      vibratoQuality: 3
      sides: 2
      deviationFunctionIndex: 1
      deviationDistance: 0
    delete:
      deleteTable:
      - true
      - true
      - true
      - true
    addTeleport:
      distance: 5000
      teleportBeforeHand: false
    changeGroups:
      designatedTimingGroup: $Default
      changeSVs: true
      changeSSFs: true
      clone: true
    completeDuplicate:
      objects:
      - 
      svTbl:
      - 
      ssfTbl:
      - 
      msOffset: 0
      dontCloneHos: true
    convertSVSSF:
      conversionDirection: true
    copyPaste:
      copyLines: false
      copySVs: true
      copySSFs: true
      copyBMs: false
      copied:
        lines:
        - - 
        SVs:
        - - 
        SSFs:
        - - 
        BMs:
        - - 
      tryAlign: true
      alignWindow: 3
      curSlot: 1
    directSV:
      selectableIndex: 1
      startTime: 0
      multiplier: 0
      pageNumber: 1
    displaceNote:
      distance: 200
      distance1: 0
      distance2: 200
      linearlyChange: false
    displaceView:
      distance: 200
    dynamicScale:
      noteTimes:
      - 
      svTypeIndex: 1
      svMultipliers:
      - 
      svDistances:
      - 
      svGraphStats:
        minScale: 0
        maxScale: 0
        distMinScale: 0
        distMaxScale: 0
      svStats:
        minSV: 0
        maxSV: 0
        avgSV: 0
    flicker:
      flickerTypeIndex: 1
      distance: -69420.726999999999
      distance1: 0
      distance2: -69420.726999999999
      numFlickers: 1
      linearlyChange: false
      flickerPosition: 0.5
    measure:
      unrounded: false
      nsvDistance: ''
      svDistance: ''
      avgSV: ''
      startDisplacement: ''
      endDisplacement: ''
      avgSVDisplaceless: ''
      roundedNSVDistance: 0
      roundedSVDistance: 0
      roundedAvgSV: 0
      roundedStartDisplacement: 0
      roundedEndDisplacement: 0
      roundedAvgSVDisplaceless: 0
    reverseScroll:
      distance: 400
    scaleBookmark:
      searchTerm: ''
      filterTerm: ''
    scaleDisplace:
      scaleSpotIndex: 1
      scaleTypeIndex: 1
      avgSV: 0.59999999999999998
      distance: 100
      ratio: 0.59999999999999998
    scaleMultiply:
      scaleTypeIndex: 1
      avgSV: 0.59999999999999998
      distance: 100
      ratio: 0.59999999999999998
    split:
      modeIndex: 1
      cloneSVs: false
      cloneRadius: 1000
    verticalShift:
      verticalShift: 1
    selectAlternating:
      every: 1
      offset: 0
    selectBookmark:
      searchTerm: ''
      filterTerm: ''
    selectByTimingGroup:
      designatedTimingGroup: $Default
    selectChordSize:
      select1: true
      select2: false
      select3: false
      select4: false
      select5: false
      select6: false
      select7: false
      select8: false
      select9: false
      select10: false
      laneSelector: 1
    selectNoteType:
      rice: true
      ln: false
      normal: true
      mine: false
    selectBySnap:
      snap: 1
disableKofiMessage: true
disableLoadup: false
dontPrintCreation: true
dontReplaceSV: false
drawCapybara: true
drawCapybara2: false
drawCapybara312: false
dynamicBackgroundIndex: 1
editToolIndex: 1
effectFPS: 100
equalizeLinear: true
hideAutomatic: true
hideSVInfo: false
hotkeyList:
- T
- Shift+T
- S
- N
- R
- B
- M
- V
- G
- Ctrl+Alt+L
- Ctrl+Alt+E
- O
ignoreNotesOutsideTg: false
maxDisplacementMultiplierExponent: 0
performanceMode: false
placeTypeIndex: 1
presets:
- 
printLegacyLNMessage: true
pulseCoefficient: 1
pulseColor:
- 0.39215686917304993
- 0
- 1
- 1
restrictSinusoidalPeriod: false
rgbPeriod: 3
scrollGroupIndex: 1
selectTypeIndex: 1
showMeasureDataWidget: true
showNoteDataWidget: true
showPresetMenu: false
showSVInfoVisualizer: true
showVibratoWidget: false
snakeSpringConstant: 0.5
stepSize: 5
styleThemeIndex: 1
upscroll: false
useCustomPulseColor: true
useEndTimeOffsets: false
useMinDisplacementMultiplier: true
ignoreNotes: false
