advancedMode: false
colorThemeIndex: 1
comboizeSelect: false
cursorTrailGhost: false
cursorTrailIndex: 1
cursorTrailPoints: 10
cursorTrailShapeIndex: 1
cursorTrailSize: 5
customStyle:
- 
defaultProperties:
  settings:
  - 
  menu:
  - 
disableLoadup: false
dontPrintCreation: false
dontReplaceSV: false
drawCapybara: false
drawCapybara2: false
drawCapybara312: false
dynamicBackgroundIndex: 1
editToolIndex: 1
effectFPS: 90
equalizeLinear: true
hideAutomatic: false
hideSVInfo: false
hotkeyList:
- T
- Shift+T
- S
- N
- R
- B
- M
- V
- G
- Ctrl+Alt+L
- Ctrl+Alt+E
- O
ignoreNotesOutsideTg: false
maxDisplacementMultiplierExponent: 6
performanceMode: false
placeTypeIndex: 1
presets:
- 
printLegacyLNMessage: true
pulseCoefficient: 0
pulseColor:
- 0
- 0
- 0
- 0
restrictSinusoidalPeriod: true
rgbPeriod: 3
scrollGroupIndex: 1
selectTypeIndex: 1
showMeasureDataWidget: false
showNoteDataWidget: false
showPresetMenu: false
showSVInfoVisualizer: true
showVibratoWidget: false
snakeSpringConstant: 1
stepSize: 5
styleThemeIndex: 1
upscroll: false
useCustomPulseColor: false
useEndTimeOffsets: false
